### ISSUE TITLE
Installation error: ‘SMRTTitle’ was not declared in this scope

### ISSUE THREAD

**Issue by zhiliangc** [PacificBiosciences/blasr#125]
I've followed the README but the installation couldn't be finished at the last step.
```
>make blasr
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/zxc561/blasr//include -I/home/zxc561/blasr/include -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o Blasr.o Blasr.cpp
In file included from /home/zxc561/blasr//include/BlasrMiscs.hpp:98:0,
                 from Blasr.cpp:38:
/home/zxc561/blasr//include/BlasrMiscsImpl.hpp: In function ‘void MakeVirtualRead(SMRTSequence&, const std::vector<SMRTSequence>&)’:
/home/zxc561/blasr//include/BlasrMiscsImpl.hpp:192:43: error: ‘SMRTTitle’ was not declared in this scope
     ss << SMRTTitle(subreads[0].GetTitle()).MovieName() << "/" << subreads[0].HoleNumber();
                                           ^
In file included from /home/zxc561/blasr//include/BlasrUtils.hpp:198:0,
                 from Blasr.cpp:39:
/home/zxc561/blasr//include/BlasrUtilsImpl.hpp: In function ‘void PrintAllReadAlignments(ReadAlignments&, AlignmentContext&, std::ostream&, std::ostream&, MappingParameters&, MappingSemaphores&)’:
/home/zxc561/blasr//include/BlasrUtilsImpl.hpp:1182:9: error: ‘subreads’ was not declared in this scope
     if (subreads.size() == allReadAlignments.subreads.size()) {
         ^
make: *** [Blasr.o] Error 1
```

**Comment by zhiliangc** [comment]
I'm using gcc (GCC) 5.2.0 and this is how my defines.mk looks like:

LIBPBDATA_LIB        ?= /home/zxc561/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /apps/hdf5/1.8.13/lib
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /apps/hdf5/1.8.13/include
LIBPBDATA_INC        ?= /home/zxc561/blasr/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBIHDF_INC        ?= /home/zxc561/blasr/libcpp/hdf
LIBBLASR_LIB         ?= /home/zxc561/blasr/libcpp/alignment
SHELL                ?= bash
BLASR_INC            ?= /home/zxc561/blasr/include
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
RT_LIBFLAGS          ?= -lrt
LIBBLASR_INC         ?= /home/zxc561/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
LIBPBIHDF_LIB        ?= /home/zxc561/blasr/libcpp/hdf
LDFLAGS+=-static

**Comment by pb-cdunn** [comment]
I forgot to update the libcpp submodule on Saturday night. But to be sure, please tell us your `configure.py` command-line and your commits:

    cd blasr
    git rev-parse HEAD
    cd libcpp
    git rev-parser HEAD

**Comment by pb-cdunn** [comment]
Yesterday's reversion (PacificBiosciences/blasr_libcpp/pull/74) might help you too.

**Comment by aaronk** [comment]
I have this same problem.  From what I can tell, the "blasr" target in the makefile depends on ${OBJS}.  The OBJS rule is a generic one that processes all of the cpp files, including Blasr.cpp, but that doesn't use the include and library variables at all.  You can see that zhiliangc's compiler command has no -lblasr, etc.

**Comment by pb-cdunn** [comment]
It's completely broken without PBBAM. We are to move the master branch back in order to undo all recent changes. Give me a minute...

**Comment by pb-cdunn** [comment]
Done. This is a rollback (`push -f`), not a *revert*. But the previous master-tip is still here as *p4-master* in case you need it.

**Comment by zhiliangc** [comment]
Here're my commits
~/blasr> git rev-parse HEAD
2551eada563a3e9caa5c19535c94582e2a0891ee
~/blasr/libcpp> git rev-parse HEAD
963859fcca47feaec7c47523157cf1c2888bad69

Here's what I did
export HDF5_INC=/apps/hdf5/1.8.13/include && export HDF5_LIB=/apps/hdf5/1.8.13/lib
./configure.py --sub --no-pbbam
Then
make build-submodule
make blasr

**Comment by zhiliangc** [comment]
Now it comes with a different error...

g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o Blasr.o Blasr.cpp
g++ -o blasr -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"blasr.d" Blasr.o -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/apps/hdf5/1.8.13/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x42e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFAtom.cpp:(.text+0x624): undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
HDFAtom.cpp:(.text+0x818): undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAttributable.o): In function `HDFAttributable::StoreAttributeNames(H5::H5Location&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
HDFAttributable.cpp:(.text+0xbf): undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFData.o): In function `HDFData::InitializeDataset(H5::CommonFG&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
HDFData.cpp:(.text+0x4f6): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x554): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x5ac): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::AddGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0xf9): undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::ContainsObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0x2e6): undefined reference to `_ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `HDFRegionTableReader::Initialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, H5::FileAccPropList const&)':
HDFRegionTableReader.cpp:(.text+0x505): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `BufferedHDF2DArray<int>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFZMWReader.o): In function `BufferedHDF2DArray<short>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/alignment/libblasr.a(ReaderAgglomerate.o):ReaderAgglomerate.cpp:(.text._ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): more undefined references to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev' follow
collect2: error: ld returned 1 exit status
make: *** [blasr] Error 1

**Comment by pb-cdunn** [comment]
You are using a wrong commit somewhere.
```
git checkout origin/master
git rev-parse HEAD
# -> 2551eada563a3e9caa5c19535c94582e2a0891ee
git submodule update
git -C libcpp rev-parse HEAD
# -> 963859fcca47feaec7c47523157cf1c2888bad69
```

**Comment by zhiliangc** [comment]
I did have the correct commit (and I did the `git checkout origin/master` anyway).
`~/blasr> git rev-parse HEAD`
`2551eada563a3e9caa5c19535c94582e2a0891ee`
`~/blasr/libcpp> git rev-parse HEAD`
`963859fcca47feaec7c47523157cf1c2888bad69`

Used the same configuration parameters and still the same error.

Just for you reference, I'm using gcc 5.2.0 and zlib 1.2.7 on SUSE Linux Enterprise Server 11 (x86_64)

**Comment by pb-cdunn** [comment]
There are only 2 ways to be missing symbols:

1. The libraries do not match their headers (for HDF5), or
2. The libraries are listed in the wrong order (for static linkage).

I see from your post that the order is fine, so it's not 2. It's possible that you have a bad HDF5 installation.

However, I do have one other idea. Instead of explaining, I'll just tell you what to do:
```
git clean -xdn
# Visually check that you will not lose anything you need.
git clean -xdf
cd libcpp
git clean -xdn
# Again, visually check.
git clean -xdf
cd ..
./configure.py <with the same args as before, AND PLEASE TELL US WHAT YOU USE>
make -j build-submodule
make -j
```

**Comment by zhiliangc** [comment]
Thanks for helping.

I did `export HDF5_INC=/apps/hdf5/1.8.13/include && export HDF5_LIB=/apps/hdf5/1.8.13/lib` to specify the path , then followed your instructions.
The configuration I used was `./configure.py --sub --no-pbbam`
It tells
`uname`
Linux
writing to '/home/zxc561/blasr/defines.mk':
"""
LIBPBDATA_LIB        ?= /home/zxc561/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /apps/hdf5/1.8.13/lib
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /apps/hdf5/1.8.13/include
LIBPBDATA_INC        ?= /home/zxc561/blasr/libcpp/pbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
LIBPBIHDF_INC        ?= /home/zxc561/blasr/libcpp/hdf
LIBBLASR_LIB         ?= /home/zxc561/blasr/libcpp/alignment
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /home/zxc561/blasr/libcpp/alignment
PTHREAD_LIBFLAGS     ?= -lpthread
LIBPBIHDF_LIB        ?= /home/zxc561/blasr/libcpp/hdf
LDFLAGS+=-static
"""
I then did 
`make -j build-submodule`
 `make -j`
And the error message

~/blasr> make -j
g++ -O3 -g -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o Blasr.o Blasr.cpp
make -C utils
make[1]: Entering directory `/home/zxc561/blasr/utils'
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o LoadPulses.o LoadPulses.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o PulseToFasta.o PulseToFasta.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o SamToCmpH5.o SamToCmpH5.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o SamToM4.o SamToM4.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o SamFilter.o SamFilter.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o ToAfg.o ToAfg.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o SAWriter.o SAWriter.cpp
g++ -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include  -c -o SDPMatcher.o SDPMatcher.cpp
g++ -o samFilter SamFilter.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"samFilter.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o sawriter SAWriter.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"sawriter.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o sdpMatcher SDPMatcher.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"sdpMatcher.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o toAfg ToAfg.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"toAfg.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o samtom4 SamToM4.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"samtom4.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o samtoh5 SamToCmpH5.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"samtoh5.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
g++ -o pls2fasta PulseToFasta.o -std=c++0x -pedantic -Wall -Wuninitialized -Wno-div-by-zero -MMD -MP -w -fpermissive  -I/home/zxc561/blasr/libcpp/alignment -I/home/zxc561/blasr/libcpp/pbdata -I/home/zxc561/blasr/libcpp/hdf -I/apps/hdf5/1.8.13/include -MF"pls2fasta.d"  -static -L/home/zxc561/blasr/libcpp/alignment -L/home/zxc561/blasr/libcpp/pbdata -L/home/zxc561/blasr/libcpp/hdf -L/apps/hdf5/1.8.13/lib -lpbihdf -lblasr -lpbdata -lpbihdf  -lhdf5_cpp -lhdf5   -lz -lrt -lpthread -ldl
/apps/hdf5/1.8.13/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x42e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAttributable.o): In function `HDFAttributable::StoreAttributeNames(H5::H5Location&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
HDFAttributable.cpp:(.text+0xbf): undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFData.o): In function `HDFData::InitializeDataset(H5::CommonFG&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
HDFData.cpp:(.text+0x4f6): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x554): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x5ac): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::AddGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0xf9): undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::ContainsObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0x2e6): undefined reference to `_ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `HDFRegionTableReader::Initialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, H5::FileAccPropList const&)':
HDFRegionTableReader.cpp:(.text+0x505): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `BufferedHDF2DArray<int>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFZMWReader.o): In function `BufferedHDF2DArray<short>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFAtom.cpp:(.text+0x624): undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
HDFAtom.cpp:(.text+0x818): undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/home/zxc561/blasr/libcpp/alignment/libblasr.a(ReaderAgglomerate.o): In function `BufferedHDF2DArray<float>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
ReaderAgglomerate.cpp:(.text._ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
ReaderAgglomerate.cpp:(.text._ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
collect2: error: ld returned 1 exit status
make[1]: *** [toAfg] Error 1
make[1]: *** Waiting for unfinished jobs....
/apps/hdf5/1.8.13/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x42e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
PulseToFasta.o: In function `BufferedHDF2DArray<float>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
PulseToFasta.cpp:(.text._ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
PulseToFasta.cpp:(.text._ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIfE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFAtom.cpp:(.text+0x624): undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
HDFAtom.cpp:(.text+0x818): undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAttributable.o): In function `HDFAttributable::StoreAttributeNames(H5::H5Location&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
HDFAttributable.cpp:(.text+0xbf): undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFData.o): In function `HDFData::InitializeDataset(H5::CommonFG&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
HDFData.cpp:(.text+0x4f6): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x554): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x5ac): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::AddGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0xf9): undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::ContainsObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0x2e6): undefined reference to `_ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `HDFRegionTableReader::Initialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, H5::FileAccPropList const&)':
HDFRegionTableReader.cpp:(.text+0x505): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFRegionTableReader.o): In function `BufferedHDF2DArray<int>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFRegionTableReader.cpp:(.text._ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIiE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFZMWReader.o): In function `BufferedHDF2DArray<short>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFZMWReader.cpp:(.text._ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIsE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
collect2: error: ld returned 1 exit status
make[1]: *** [pls2fasta] Error 1
/apps/hdf5/1.8.13/lib/libhdf5.a(H5PL.o): In function `H5PL_load':
H5PL.c:(.text+0x42e): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAlnInfoGroup.o): In function `BufferedHDF2DArray<unsigned int>::Initialize(HDFGroup&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, int, bool)':
HDFAlnInfoGroup.cpp:(.text._ZN18BufferedHDF2DArrayIjE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIjE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x455): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFAlnInfoGroup.cpp:(.text._ZN18BufferedHDF2DArrayIjE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib[_ZN18BufferedHDF2DArrayIjE10InitializeER8HDFGroupNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjib]+0x4f4): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFAtom.cpp:(.text+0x624): undefined reference to `H5::Attribute::write(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAtom.o): In function `HDFAtom<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
HDFAtom.cpp:(.text+0x818): undefined reference to `H5::Attribute::read(H5::DataType const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFAttributable.o): In function `HDFAttributable::StoreAttributeNames(H5::H5Location&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
HDFAttributable.cpp:(.text+0xbf): undefined reference to `H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFData.o): In function `HDFData::InitializeDataset(H5::CommonFG&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
HDFData.cpp:(.text+0x4f6): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x554): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
HDFData.cpp:(.text+0x5ac): undefined reference to `_ZNK2H59Exception12getDetailMsgB5cxx11Ev'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::AddGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0xf9): undefined reference to `H5::CommonFG::createGroup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const'
/home/zxc561/blasr/libcpp/hdf/libpbihdf.a(HDFGroup.o): In function `HDFGroup::ContainsObject(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
HDFGroup.cpp:(.text+0x2e6): undefined reference to `_ZNK2H58CommonFG15getObjnameByIdxB5cxx11Ey'
collect2: error: ld returned 1 exit status
make[1]: *** [samtoh5] Error 1
make[1]: Leaving directory `/home/zxc561/blasr/utils'
make: *** [makeutils] Error 2
make: *** Waiting for unfinished jobs....

**Comment by pb-cdunn** [comment]
> undefined reference to `H5::H5Location::

I think that might mean your HDF5 was not installed with extra C++ support. Let me look for an old ticket related to this...

**Comment by pb-cdunn** [comment]
You're having the same problem as #116. But that was never solved. You both have problems with your HDF5 installation. Maybe try installing the latest HDF5:
* ftp://www.hdfgroup.org/HDF5/current/src/unpacked/release_docs/INSTALL_CMake.txt

**Comment by pb-cdunn** [comment]
For comparison, here is my HDF5:
```
blasr:master$ ls hdf5/include
H5AbstractDs.h  H5CommonFG.h   H5DcreatProp.h  H5Exception.h   H5FDmpio.h      H5Fpublic.h      H5Library.h   H5PacketTable.h  H5Rpublic.h     hdf5.h
H5ACpublic.h    H5CompType.h   H5DOpublic.h    H5FaccProp.h    H5FDmpiposix.h  H5Gpublic.h      H5Location.h  H5PLextern.h     H5Spublic.h     hdf5_hl.h
H5api_adpt.h    H5CppDoc.h     H5Dpublic.h     H5FcreatProp.h  H5FDmulti.h     H5Group.h        H5Lpublic.h   H5Ppublic.h      H5StrType.h
H5Apublic.h     H5Cpp.h        H5DSpublic.h    H5FDcore.h      H5FDpublic.h    H5IdComponent.h  H5LTpublic.h  H5PredType.h     H5TBpublic.h
H5ArrayType.h   H5Cpublic.h    H5DxferProp.h   H5FDdirect.h    H5FDsec2.h      H5IMpublic.h     H5MMpublic.h  H5PropList.h     H5Tpublic.h
H5AtomType.h    H5DataSet.h    H5EnumType.h    H5FDfamily.h    H5FDstdio.h     H5Include.h      H5Object.h    H5PTpublic.h     H5VarLenType.h
H5Attribute.h   H5DataSpace.h  H5Epubgen.h     H5FDlog.h       H5File.h        H5IntType.h      H5Opublic.h   H5pubconf.h      H5version.h
H5Classes.h     H5DataType.h   H5Epublic.h     H5FDmpi.h       H5FloatType.h   H5Ipublic.h      H5overflow.h  H5public.h       H5Zpublic.h
blasr:master$ ls hdf5/lib
libhdf5.a      libhdf5_cpp.so    libhdf5_cpp.so.8.0.1  libhdf5_hl_cpp.a   libhdf5_hl_cpp.so.8      libhdf5_hl.so    libhdf5_hl.so.8.0.1  libhdf5.so.8
libhdf5_cpp.a  libhdf5_cpp.so.8  libhdf5_hl.a          libhdf5_hl_cpp.so  libhdf5_hl_cpp.so.8.0.1  libhdf5_hl.so.8  libhdf5.so           libhdf5.so.8.0.1
```

**Comment by pb-cdunn** [comment]
On my mac, I use HDF5-1.8.14 with no problems, and internally we use 1.8.13. I don't think the version is the problem though. It's something about the installation. Maybe you installed C++ headers but you didn't actually build with C++ support. Someone had your problem in #28 and resolved it by using 1.8.9.

Would you show us the contents of your hdf5/lib directory? Then:

    nm <dir>/lib/libhdf5_cpp.a | grep iterateAttrs

You should see:

    0000000000000956 T _ZN2H510H5Location12iterateAttrsEPFvRS0_SsPvEPjS2_

    $ c++filt _ZN2H510H5Location12iterateAttrsEPFvRS0_SsPvEPjS2_
    H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)

Please post your actual result, so we can see the signature of the missing function.

**Comment by pb-cdunn** [comment]
I have to go to sleep, but please let us know whatever you learn. This problem keeps recurring, and it doesn't seem to be a bug in our code. There must be some small problem that is common in many HDF5 installations. If I could reproduce it, I could solve it.

**Comment by zhiliangc** [comment]
Sorry for keeping you waiting, I'm in Australia and was on my way home.
I'll check it now and post my results.

**Comment by zhiliangc** [comment]
Here's my HDF5
~/blasr> ls /apps/hdf5/1.8.13/include/
H5AbstractDs.h         h5e.mod              h5g.mod                h5p.mod
H5ACpublic.h           H5EnumType.h         H5Gpublic.h            h5p_provisional.mod
h5a.mod                h5e_provisional.mod  H5Group.h              H5Ppublic.h
H5api_adpt.h           H5Epubgen.h          H5IdComponent.h        H5PredType.h
h5a_provisional.mod    H5Epublic.h          h5im.mod               H5PropList.h
H5Apublic.h            H5Exception.h        h5i.mod                H5PTpublic.h
H5ArrayType.h          H5f90i_gen.h         H5IMpublic.h           H5pubconf.h
H5AtomType.h           H5f90i.h             H5Include.h            H5public.h
H5Attribute.h          H5FaccProp.h         H5IntType.h            h5r.mod
H5Classes.h            H5FcreatProp.h       H5Ipublic.h            h5r_provisional.mod
H5CommonFG.h           H5FDcore.h           h5lib.mod              H5Rpublic.h
H5CompType.h           H5FDdirect.h         h5lib_provisional.mod  h5s.mod
H5CppDoc.h             H5FDfamily.h         H5Library.h            H5Spublic.h
H5Cpp.h                H5FDlog.h            h5l.mod                H5StrType.h
H5Cpublic.h            H5FDmpi.h            H5Location.h           h5tb.mod
H5DataSet.h            H5FDmpio.h           h5l_provisional.mod    H5TBpublic.h
H5DataSpace.h          H5FDmulti.h          H5Lpublic.h            h5test_kind_sizeof_mod.mod
H5DataType.h           H5FDpublic.h         h5lt.mod               h5t.mod
h5_dble_interface.mod  H5FDsec2.h           H5LTpublic.h           h5t_provisional.mod
H5DcreatProp.h         H5FDstdio.h          H5MMpublic.h           H5Tpublic.h
h5d.mod                H5File.h             H5Object.h             H5VarLenType.h
H5DOpublic.h           H5FloatType.h        h5o.mod                H5version.h
h5d_provisional.mod    h5f.mod              h5o_provisional.mod    h5z.mod
H5Dpublic.h            h5fortran_types.mod  H5Opublic.h            H5Zpublic.h
h5ds.mod               h5f_provisional.mod  H5overflow.h           hdf5.h
H5DSpublic.h           H5Fpublic.h          H5PacketTable.h        hdf5_hl.h
H5DxferProp.h          h5global.mod         H5PLextern.h           hdf5.mod

**Comment by zhiliangc** [comment]
And  the contents of my hdf5/lib directory
```
~/blasr> nm /apps/hdf5/1.8.13/lib/libhdf5_cpp.a | grep iterateAttrs
0000000000000702 T _ZN2H510H5Location12iterateAttrsEPFvRS0_SsPvEPjS2_
~/blasr> c++filt _ZN2H510H5Location12iterateAttrsEPFvRS0_SsPvEPjS2_
H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)
```

**Comment by zhiliangc** [comment]
We have 
```
hdf5/1.8.10 
hdf5/1.8.10-intel 
hdf5/1.8.13
```
installed on the server at the moment, I can probably try 1.8.10? Otherwise I can get our system admin to  install a latest version for me.

**Comment by pb-cdunn** [comment]
I see the problem now. Your linker is looking for:

    H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)

but you have

    H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)

That's the problem we need to solve. First, try `make` without `-j`, since your errors are coming from the *utils* sub-directory. I'd like to see whether `blasr` itself can be linked.

In the meantime, I'll look into this problem. My initial guess is that your HDF5 library was compiled with neither `--std=c++0x` nor `--std=c++11`. You might have to re-install HDF5 with one of those, or use a compiler which makes that standard.

**Comment by pb-cdunn** [comment]
Aha. **Julia** [has the same problem](https://github.com/JuliaLang/julia/issues/10201). The solution seems to be adding `-D_GLIBCXX_USE_CXX11_ABI=1` to the blasr build on some systems. Not sure though. What Linux are you using? Fedora?

**Comment by armintoepfer** [comment]
It's more a question of "are you using gcc >5 and did not compile it with the old ABI"? :)

**Comment by pb-cdunn** [comment]
Oh, I said it wrong. Your HDF5 was built with the older gcc/ABI.

And yes, Armin, that is one solution. Is that the best recommendation?

**Comment by armintoepfer** [comment]
Either use the workaround or compile hdf with your new gcc.

**Comment by pb-cdunn** [comment]
* https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by zhiliangc** [comment]
I used the same version of hdf5 but recompile blasr using `gcc 4.9.0` and now it's working! 
Thanks a lot everyone.
