### ISSUE TITLE
samtoh5 error / exceptionally long blasr run-time

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/blasr#225]
Hi,

I am trying to analyze a sample (or, actually, 4 barcoded samples within 1 run) for base-modification analysis, and I am aligning my pacbio reads against a single plasmid reference sequence.  I have tried the following alignment strategies:

1) **blasr** via pbalign (.fofn to cmd.h5, with --forQuiver option)
2) **bowtie2** via pbalign (.fofn to cmd.h5, with --forQuiver option)
3) **gmap** via pbalign (.fofn to cmd.h5, with --forQuiver option)
4) direct **blasr**  alignment with all subreads (.fofn to .sam)
5) direct **blasr** alignment with all CCS reads (.fofn to .sam)
6) direct **blasr** alignment with all subreads (.fasta to .sam)
7) direct **blasr** alignment with all CCS reads (.fasta to .sam)
8) down-sampled 5 read **blasr** alignment with subreads (.fasta to .sam)
9) down-sampleed 5 read **blasr** alignment with CCS reads (.fasta to .sam)

The blasr alignments with the full set of reads (alignment strategies 1 and 4-7) have been running for about a day, which seems too long given the number of reads (61,514 subreads and 7,640 CCS reads).  I can get BLAST hits against the plasmid reference for 85.4% of subreads and 13.4% of CCS reads within a few minutes (the low number of CCS BLAST hits is probably because of the very small size of the CCS reads, the majority of the CCS reads are less than 50 nt).

It looks like the alignment step runs OK for the non-blasr alignments (in about an hour), but I get the following error messages:

bowtie alignment:

     [INFO] 2016-04-15 16:27:07,556Z [root _output 214] OutputService: Genearte the output CMP.H5 file using samtoh5.
     [DEBUG] 2016-04-15 16:27:07,557Z [root _output 223] OutputService: Call "samtoh5 /tmp/tmpu_rq8V/YtbumZ.sam /Volumes/user_data/Seq/core_test/pacbio/DNA_methylation/pDmeth.fa /Volumes/user_data/Seq/core_test/pacbio/DNA_methylation/methTest.fofn.bowtie.cmp.h5 -readType standard  -smrtTitle "
     samtoh5 returned a non-zero exit status.
     [ERROR] 2016-04-15 16:27:07,913Z [root _output 241] samtoh5 returned a non-zero exit status.
     [INFO] 2016-04-15 16:27:07,914Z [pbalign.pbalignrunner _pacbio_main_runner 152] exiting with return code 1 in 3182.72 sec.

gmap alignment:  

     [INFO] 2016-04-15 16:31:31,503Z [root _output 214] OutputService: Genearte the output CMP.H5 file using samtoh5.
     [DEBUG] 2016-04-15 16:31:31,503Z [root _output 223] OutputService: Call "samtoh5 /tmp/tmpMk_jMd/LaF8cO.sam /Volumes/user_data/Seq/core_test/pacbio/DNA_methylation/pDmeth.fa /Volumes/user_data/Seq/core_test/pacbio/DNA_methylation/methTest.fofn.gmap.cmp.h5 -readType standard  -smrtTitle "
     samtoh5 returned a non-zero exit status.
     [ERROR] 2016-04-15 16:31:31,638Z [root _output 241] samtoh5 returned a non-zero exit status.
     [INFO] 2016-04-15 16:31:31,638Z [pbalign.pbalignrunner _pacbio_main_runner 152] exiting with return code 1 in 2670.48 sec.

Since the problem appears to be with samtoh5 (which is compiled from the blasr code), I figured this might still be relevant for this discussion group.

The 5 CCS reads do not yield any blasr alignment (probably due to the small read length, I'm not so worried about this).  I can get a .sam file from the 5 subread blasr alignment, but I noticed that there are a lot of gaps.  For example, see one read from the alignment below:

     m160407_175515_42284_c100875832550000001823187303261636_s1_X0/163465/56797_58537/0_1740	0	pDmeth	4978	254	28M1D15M1D33M1D11M1D13M1I12M3I37M1I4M1I9M1D7M1I1M1I3M1D12M3D24M1D14M1I16M1I2M2I4M1I3M1I11M1D1M1D1M1D27M1D16M1I13M1I10M1I5M1I2M1I22M1D9M1I4M1I4M1I14M1D9M1I8M1D21M1D11M1D3M1D8M1D21M1D2M1I7M1D40M1D7M1I4M1I32M1D10M1D3M1I3M1I19M1D6M1I25M1D11M1I37M1D19M1D29M1I5M1I3M1D22M3I21M1I20M1I5M1I9M2D34M1D5M1I7M2I6M1I50M1I15M2I26M1I18M1I5M1D8M1I11M1I3M1I26M1I18M1D1M1D16M1I7M1I4M1I5M1D24M1D6M1I19M1I18M1I30M1D29M1D9M1I12M1I14M1I5M1I29M1I5M1I18M1D12M1D31M1I7M1I17M1D5M1I17M1I56M2D8M1I3M1D4M2I5M1I3M2I3M1D2M1I12M1I19M1I6M1I11M2I44M1I24M1I4M3I6M2I2M1D16M1D16M1I6M1D7M	*	0	0	ACTTGTTTAGGGTTAGAGCTGCCCCCTCGGGGACCAGGATTGTCAGCCAAGGCCATTGTCCTGCCCCCTTCCCCCATCCCTCCCAGGCCCTTTGAACCTGAAAGTCAGATATTACATCTTCTCTCTACCCACCTCCCACCCGTTGGGTTTCTCTCACCTCAGGAACTAGCTGGAAGGCCCTGGATGAGGAGGTGGGAGGTAGAACTGAGAATCTTGAGAAAGAGGCCCCGGCCCTAAACTGTGAGGGGAATGGGGAGCCCTCGGGTGCAGGTCTTGGGGTTGGGGGGTGGTTAGTGTCTAATTACCAACCTGGACAACAACAAGATGGAATATCTGTGCTCTGAAAAACGGCAAGAGCCAGCACTTTTCTGGGGTTCTGGGGACAATATCCTGGCTTGGGGCTCGGGGTCCATGGTGTAAGAGCCTCAAACTCTGGAGGACTGGAGGTCAATGGCTGTCTGTCTGGCCTTGACATGGGCTGAAATACTGGGTCAACCCATACTAGGACTCTAGACGGGTGGGTAAGCAAGAACTGAGGAGTGCCCCAGAAAATAAATTGGCACACGAACATTCAATGGATGTTTTAGCTCTCCAGAGATGGGCTTGAGTGGGCTGTAAGGACAGCCGAGAAGGGTGCAGTGCCAACAGGCTTTGTGTGCGATGGGGCCATCCGAGCAACTGGTTTGTGAGGTGTCCGGTGAACCAGGCAGGGGTGAGAGGACCTGAAGGTTGAAAATGAAGGCCTCCTGGGGTTCCCGTTCCAAGGGTTGTCCTGTCCAGACGTCCCCCCCAACCTCCGTCTGGAAGACCACAGGCCGATAGCGCTCGCACTCAGTTTTCTCCCACCCACAGCTCTGCTCCTCCACCCACGCAGGGGGCGGGCCTAGAGGTCAAAAGGCTAAGAGGGTGGGATTGGGGAGGGAGAGGTGAAACCGTCCCTAGGTGAGCCGTCCTTTCCACCAGGCCCTGCCGGCTCGGGGTGCCCACCTTCCCCGAAATTCTGCAGTCGACGGTAACCGCGGCCCGGGAATCCACCGGCCGGGTCCGCCACCATGGTGAGCAAAGGCGAGGAAGCTGTTCACCGGGGTGGGCCATCCTGGTCGAGCTGGGACGGCGGACGCTAAACGCCACAAGTTCAGCGTGTCCGGCGGGGCGAGGGGCGATGCCACCTACGGCAAAGCTGACCCTGAAGTTCAATCTGCACCACCGGCAAGCTGCCCGTGCCCGGCCCACCCTCGTGACCACCCTGACCTACGCGTGCAGTGGCTTCAGCCGCTAACCCCGACCACATGAAAGCATGCACGACTTCTTCAAGTCCGCCATGCCCGAAAGGCTTACGTCCATGAGCGCACCTCTTCTTCAAAGCGACCGCAACTACAAGACCCGCGCCGAGGTGAAAGTTCGTAGGGCGACACCCTGGTGACCGCAATCGAGCTGAAGGGCATGCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGAAGTACAACTACAACACACAACGTCCTAATCATGTGGCCAGACATAAGAGAAAGAACGGCATCAAAGGTGAACTTCAAGATCCAGCCACAGACATCGAGGACTAGGCAACGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCCGGCGACGGCCCCGTGCTGCTGCCTCGACAAAAAACACTGTACTGAGCACCCAGTCCGCCTGAGCAAAGACCCCAAACGAGAGCGCGA	*	RG:Z:cc91917c	AS:i:-7347	XS:i:18	XE:i:1741	YS:i:0	YE:i:1740	ZM:i:0	XL:i:1723	XT:i:1	NM:i:151	FI:i:18	XQ:i:1740

I'm not sure if this is the problem, but I thought it might be helpful to provide this information.

Can you please help me troubleshoot?  For example, is there an alternative set of blasr parameters to use when encountering such a long run time?  Can you help me identify the problem with samtoh5 (which I probably need no matter what, since I would like to get a .cmp.h5 file for barcode and base-modification analysis)?

Thanks,
Charles

**Comment by cwarden45** [comment]
To give you an update, I went back to the temporary .sam files for bowtie2 and gmap:

1) bowtie2 doesn't successfully align any reads (they all go in an unmapped .sam file).

2) gmap does align a fair number of reads, so I tried running samtoh5 on that alignment.  However, I get the following error message (for each of the variants from the pbalign command):

     cwarden$ samtoh5 pbalign.gmap.1.sam pDmeth.fa gmap.aligned.cmp.h5 -readType standard -smrtTitle
     [INFO] 2016-04-15T11:55:20 [samtoh5] started.
     Segmentation fault: 11
     cwarden$ samtoh5 pbalign.gmap.1.sam pDmeth.fa gmap.aligned.cmp.h5 -readType standard
     [INFO] 2016-04-15T11:59:26 [samtoh5] started.
     Segmentation fault: 11
     cwarden$ samtoh5 pbalign.gmap.1.sam pDmeth.fa gmap.aligned.cmp.h5
     [INFO] 2016-04-15T11:59:31 [samtoh5] started.
     Segmentation fault: 11

3) I'm also playing around with some blasr parameters like -minMatch and -maxAnchorsPerPosition, but no quick alignment yet...

I hope this is helpful for at least troubleshooting the samtoh5 problem ....

**Comment by mchaisso** [comment]
Hi Charles, would you be willing to share a few reads + the plasmid?

-mark

**Comment by cwarden45** [comment]
Sure - I've attached a .zip file with the reference and a file with 5 subreads that can successfully be aligned using blasr.

I get the same segmentation fault error with the samtoh5 command as I did with the gmap alignment.

[troubleshoot.zip](https://github.com/PacificBiosciences/blasr/files/221675/troubleshoot.zip)

**Comment by cwarden45** [comment]
I should probably also mention that I am running my analysis on a mac with blasr installed as described in https://github.com/PacificBiosciences/blasr/issues/217

If I sort the truncated .sam file, then I am able to successfully run samtoh5 on a Linux server.

**Comment by cwarden45** [comment]
Hi again - I've noticed that I can run blasr on the Linux server (using the same number of processors) much more quickly than on my mac (default setttings, in both cases).

So, I think the long run-time and the samtoh5 error may be related to each other.

I tried to use homebrew to install blasr (as mentioned in this post https://github.com/PacificBiosciences/blasr/issues/62 to fix a segmentation error in samtoh5), but I get an error message that blasr can't be installed with homebrew.

     cwarden$ brew install hdf5 --cc=gcc-4.8 --c++11
     Warning: homebrew/science/hdf5-1.8.16_1 already installed
     cwarden$ brew instal blasr --cc=gcc-4.8
      ==> Installing blasr from homebrew/science
     Error: The requested Homebrew GCC was not installed. You must:
        brew install homebrew/versions/gcc48
      cwarden$ brew install homebrew/versions/gcc48
      ==> Installing gcc48 from homebrew/versions
      ==> Downloading https://homebrew.bintray.com/bottles-versions/gcc48-4.8.5.el_cap
      ######################################################################## 100.0%
      ==> Pouring gcc48-4.8.5.el_capitan.bottle.tar.gz
      Error: The `brew link` step did not complete successfully
      The formula built, but is not symlinked into /usr/local
      Could not symlink share/man/man7/fsf-funding-4.8.7
       /usr/local/share/man/man7 is not writable.

     You can try again using:
        brew link gcc48
     ==> Summary
      /usr/local/Cellar/gcc48/4.8.5: 1,045 files, 147.5M
       cwarden$ brew link gcc48
      Linking /usr/local/Cellar/gcc48/4.8.5... 
      Error: Could not symlink share/man/man7/fsf-funding-4.8.7
      /usr/local/share/man/man7 is not writable.

Is there an alternative solution?  I'd like to have a local working copy of blasr.

**Comment by mchaisso** [comment]
Hmm, I see:
time blasr reads.fasta pDmeth.fa -sam > aln.sam
[INFO] 2016-04-15T13:57:51 [blasr] ended.

real 0m0.083s
user 0m0.033s
sys 0m0.003s

Of this, rougly 0.036 s are startup and I/O.

**Comment by cwarden45** [comment]
Ok - thank you for checking that.  Can you reproduce my samtoh5 error (on a mac)?

Also, I noticed that the version of blasr that can complete within an hour on the Linux server is very different than that I am trying to use on the mac:

Linux server: blasr version 1.3.1
local Mac: blasr version 5.0.26fcee5

Not sure why the alignment would be slower on the newer version, but thought I should provide this info.

On the other hand, the versions of samtoh5 seem to be more similar, so I'm guessing it is a compilation problem?

Linux server: samtoh5 version 1.0.0.126414
local Mac: samtoh5 version 1.0.0.141782

**Comment by mchaisso** [comment]
I typically just check in on performance issues with blasr. Regarding the
samtoh5, I don't have a mac.

**Comment by pb-cdunn** [comment]
```
Error: Could not symlink share/man/man7/fsf-funding-4.8.7
  /usr/local/share/man/man7 is not writable.
```
Make it writable. Homebrew requires write access to all of `/usr/local`. If you're worried, you can create a homebrew user.

**Comment by cwarden45** [comment]
Hi Christopher - Ok, I've made the directory writable, but I still can't install blasr via homebrew because it is not using the version that I installed.  I updated the path to first check the location of the binary of the homebrew version of gcc (which can get run via 'gcc-4.8'), but this is not sufficient to link the latest version of gcc.

```
cwarden$ brew instal blasr --cc=gcc-4.8
==> Installing blasr from homebrew/science
Error: The requested Homebrew GCC was not installed. You must:
  brew install homebrew/versions/gcc48
cwarden$ brew install homebrew/versions/gcc48
Warning: homebrew/versions/gcc48-4.8.5 already installed, it's just not linked
 cwarden$ gcc
clang: error: no input files
cwarden$ which gcc
/usr/bin/gcc
cwarden$ gcc-4.8
gcc-4.8: fatal error: no input files
compilation terminated.
cwarden$ echo $PATH
/usr/local/Cellar/gcc48/4.8.5/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/ncbi/blast/bin:/usr/local/mysql/bin:/usr/local/Cellar/git/2.8.0/bin
```

Can you please help point out what I am doing wrong with the homebrew gcc installation?

**Comment by pb-cdunn** [comment]
Please file build problems as a separate Issue. In fact, you can probably google solutions for **homebrew**.

We cannot solve all integration problems, but we do have a system that works on several systems. If you are frustrated with your own system, you might try this:
* https://github.com/PacificBiosciences/pitchfork/wiki

**Comment by mhsieh** [comment]
I will help you if you switch to pitchfork.

**Comment by cwarden45** [comment]
1) Ok - I can successfully install blasr via homebrew using gcc-4.9 (at least without getting any error messages, which was also the case with my version of blasr installed from github).

2) If I use the version of blasr that I previously compiled, then I get error messages saying that blasr can't open the input files

3) If I use the newly compiled (homebrew) version of blasr with the parameters used by pbalign:

     /usr/local/Cellar/blasr/2.2/bin/blasr temp.fofn pDmeth.fa -out mac.blasr.pbalign.param.sam  -sam  -nproc 4 -bestn 10 -minMatch 12  -nproc 2  -minSubreadLength 50 -minAlnLength 50  -minPctSimilarity 70 -minPctAccuracy 70 -hitPolicy randombest  -randomSeed 1

I get an error message:

      ERROR: minAlnLength is not a valid option.

4) If I use the complied (homebrew) version of blasr, it starts running.  I will check if it is able to complete the alignment within an hour (and update this posting)

However, even if strategy #4 works, I need to be able to create an cmp.h5 file with the IPD and PulseWidth tags.  While I doubt this parameter is crucial for accomplishing this, it looks like there are some differences between the version of blasr on homebrew and github (and I need a file that is comparable to the --forQuiver option from pbalign (using blasr).  In fact it looks like the versions are quite different:

```
cwarden$ /opt/blasr_install/blasr/blasr -version
blasr	5.0.26fcee5
cwarden$ /usr/local/Cellar/blasr/2.2/bin/blasr -version
blasr	1.3.1
```

Is there a way to configure the homebrew version of blasr that is compatible with pbalign (and/or produce the same type of output file)?  If not, then I'll need to go back to my previously compiled version of blasr and/or try compiling blasr with pitchfork.

**Comment by vrainish-pacbio** [comment]
Hi ,

cwarden$ /usr/local/Cellar/blasr/2.2/bin/blasr -version
blasr   1.3.1

This is an older version of Blasr, please, don't to use it.

In general, in view of your problems,
I strongly advise you to use pitchfork. It's a self-contained build environment which ensure
every component and tool are compatible with each other. While it might take a little bit longer for initial install, its very much worth it and will save you a lot of time

**Comment by pb-cdunn** [comment]
The **homebrew** blasr is supported (or created and not supported) by someone outside PacBio. I guess you could look into updating it. We definitely don't support it.

**Comment by vrainish-pacbio** [comment]
Adding to my previous comments 

A simple blasr install as described in the blasr wiki example , works for overwhelming majority of users. Base on latest experience , most of the build problems were solved by just doing clean install of most recent blasr version and related tools.  In a few cases of some specific build environments it's not enough. Pitchfork is designed ( in addition to other things) to help in such cases.

**Comment by cwarden45** [comment]
Ok - thanks.

I've re-complied the original github code and I've started a blasr alignment.

I'm running the alignment on only files saved on my local drive to see if that helps with the run-time.  I've noticed that I still get the segmentation fault with samtoh5, so I suspect that blasr will get stuck again.  However, I'll wait until tomorrow to test a pitchfork-installed version of blasr (just in case I can separate the run-time and samtoh5 issues).

**Comment by cwarden45** [comment]
The re-compiled blasr file can now run with a reasonable run-time (within 1 hr, both for local hard drive and network drive).  So, that solves 1/2 of the problem!

However, samtoh5 still gives the same segmentation error:

```
cwarden$ /opt/blasr/utils/samtoh5 blasr.sam ref.fa blasr.cmp.h5
[INFO] 2016-04-19T12:21:14 [samtoh5] started.
Segmentation fault: 11
```

I am trying to compile blasr with pitchfork in order to help troubleshoot the samtoh5 problem, but I am currently having problems getting pitchfork to work: https://github.com/PacificBiosciences/pitchfork/issues/221

**Comment by cwarden45** [comment]
FYI, I also get the same segmentation error with loadPulses

```
cwarden$ loadPulses file.bas.h5 ccs.blasr.cmp.h5 
[INFO] 2016-04-19T13:26:41 [loadPulses] started.
Segmentation fault: 11
```

**Comment by cwarden45** [comment]
Ok - I've tried compiling blasr via pitchfork.

This fixes the original segmentation error, but I am now getting a different error message (which is the same for samtoh5 and loadPulses):

libc++abi.dylib: terminating with uncaught exception of type H5::PropListIException

Can you help me troubleshoot this issue?

**Comment by cwarden45** [comment]
With some assistance from the pitchfork thread, I was able to fix this error message my re-compiling blasr with HAVE_HDF5 = /usr/local/Cellar/hdf5/1.8.16_1 in the settings.mk file

I no longer get the same error message with loadPulses (I get a different error message, but I'll list that as a separate issue).

Thanks for your help!

**Comment by cwarden45** [comment]
FYI, it looks like my "long run-time" problem was due to the way that I had ccache installed.  See https://github.com/PacificBiosciences/blasr/issues/232

At least with respect to the "long run-time" issue, using the standard output instead of -out was also a work-around solution.  However, this output was still incompatible with samtoh5 (with the non-pitchfork, non-pbbam version of blasr), so this looks like it is only a partial solution.
